import '@/app/globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header'


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Authjs 5: Middleware',
//   description: 'Generated by create next app',
// }
export const metadata = {
  title: 'ORM Prisma',
  description: 'Generated by create next app',
  manifest: '/manifest.json'
}

export default async function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className='bg-cover bg-center' style={{backgroundImage: "url('bicicleta.jpg')"}}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
